# Configuration for running FCM test battery on Travis CI
# See https://travis-ci.org/ for more info.

---
dist: xenial
language: perl
perl:
    - "5.26"
    - "5.28"
    - "5.30"

before_install:
    - echo "export PATH=${PWD}/bin:\${PATH}" >>"${HOME}/.bashrc"
    - echo "#!/bin/bash" >"${PWD}/bin/gfortran"
    - echo 'exec gfortran-9 "$@"' >>"${PWD}/bin/gfortran"
    - chmod +x "${PWD}/bin/gfortran"
    - source "${HOME}/.bashrc"

install: 
    - sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test'
    - sudo apt update
    - sudo apt install -y 'build-essential' 'gfortran-9'
    - sudo apt install -y 'libconfig-inifiles-perl' 'libxml-parser-perl'
    - sudo apt install -y 'libdbi-perl' 'libdbd-sqlite3-perl'
    - sudo apt install -y 'subversion' 'python-subversion' 'libsvn-perl'
    - sudo apt install -y 'heirloom-mailx'
    - sudo apt install -y 'python-pip'
    - sudo pip install 'trac'
    - cpanm 'Config::IniFiles' 'DBI' 'DBD::SQLite' 'XML::Parser'

script: 
    - fcm test-battery -j 5
